# Generated by Django 4.2.4 on 2024-03-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0005_alter_recorrido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='descripcion',
            field=models.CharField(max_length=1500),
        ),
    ]
