# Generated by Django 4.2.4 on 2024-03-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0006_recorrido_activo_alter_recorrido_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorrido',
            name='activo',
        ),
    ]
