# Generated by Django 4.2.4 on 2024-03-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrido', '0007_remove_recorrido_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
