# Generated by Django 4.2.4 on 2024-03-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0009_remove_transaccion_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
