# Generated by Django 4.2.4 on 2024-03-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pInteres', '0003_puntointeres_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntointeres',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
