# Generated by Django 4.2.4 on 2024-04-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pInteres', '0005_alter_puntointeres_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntointeres',
            name='modelo',
            field=models.FileField(blank=True, null=True, upload_to='modelos'),
        ),
    ]
